id: "simple-service"
dir: "./example-config/services/simple-service"
blocks:
  - id: build
    type: cmd-seq
    commands:
      - executable: /usr/bin/python3
        args:
          - simulate-build.py
      - executable: /usr/bin/python3
        args:
          - simulate-assemble.py
    status_line:
      symbol: Bld
      slot: 20
    health:
      requirements:
        - type: file
          paths:
            - build/build-artifact.example
  - id: run
    type: process
    command:
      executable: /usr/bin/python3
      args:
        - run.py
    prerequisites:
      - type: state
        query: self.build.status == OK
    status_line:
      symbol: Run
      slot: 10
    health:
      timeout: 20s
      requirements:
        - type: port
          port: 8000
        - type: http
          timeout: 500ms
          method: GET
          url: http://localhost:8000/status
          status: 200
tasks:
  - id: "Clean restart"
    steps:
      - action: cancel("build")