id: "simple-service"
dir: "./example-config/services/simple-service"
blocks:
  - id: "build"
    type: "cmd-seq"
    status_line:
      symbol: "Bu"
      slot: 10
    commands:
      - executable: "/usr/bin/python3"
        args:
          - "simulate-build.py"
